# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f96e68152a285914c28cf83a50951132e566fbd4aff3819ad26cc8d1c1fc78e09c3e4d20c08476598e52719e14fae83936321ee9665b046b1c23b1a1c683ee

test:
  secret_key_base: 3480ef925a93a1916cc4e381d8f5b6a2980e74aace83c5777627c6c283acc9eeb8329384889dd2dcbb6f535132bb3bb09732768ec5825667c388668f72f53369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
